[package]
name = "generator"
version = "0.0.0"
authors = ["Myriad Dreamin"]
repository = "https://github.com/Myriad-Dreamin/dapts"
license = "MIT"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
indexmap = "2"

[lints.clippy]
uninlined_format_args = "warn"
